name: Continuous Delivery
on: push
# Updated YAML file

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: npm i && npm run build
