name: Continuous Delivery
on: push
# Updated YAML file

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Dependencies
        run: npm i
      - name: Build
        run: npm i && npm run build

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Dependencies
        run: npm i
      - name: Run Unit Tests
        run: npm t

  security-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Check for security issues
        run: npm audit --audit-level=critical
  
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: typescript
      - name: Perform Analysis
        uses: github/codeql-action/analyze@v1
